name: 'codedeploy'

run-name: Deploy to EC2

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  ready:
    runs-on: ubuntu-latest
    steps:
      - run: echo "bulid start"
  build:
    name: "codedeploy"
    runs-on: ubuntu-latest
    needs: ready
    if: ${{ contains(github.event.head_commit.message, deploy) }}   
    steps:       
      - name: checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}      
      - name: make zip
        run: |
          cd script
          zip codedeploy.zip *      
      - name: upload to S3
        run: |
          cd script
          aws s3 cp codedeploy.zip s3://devopsmason-terraform/test20221014/
          rm -rf codedeploy.zip          
      - name: request to Codedeploy
        run: |
          aws deploy create-deployment --application-name code-deploy --deployment-group-name test --s3-location bucket=devopsmason-terraform,key=test20221014/codedeploy.zip,bundleType=zip
